### ISSUE TITLE
real-time gcc-nmf error?

### ISSUE THREAD

**Issue by dankorg** [seanwood/gcc-nmf#4]
I am trying to make the real-time gcc-nmf work, I have the correct data paths, etc, the script created the pretrained files. The following error appears after starting the script after:

C:\gccNMF>python demo5.py
INFO:root:GCCNMFConfig: loading configuration params...
INFO:root:TDOA
INFO:root:    targetTDOAEpsilon: 5.0
INFO:root:    targetTDOANoiseFloor: 0.0
INFO:root:    numSpectrogramHistory: 128
INFO:root:    microphoneSeparationInMetres: 0.1
INFO:root:    numTDOAs: 64
INFO:root:    numTDOAHistory: 128
INFO:root:    targetTDOABeta: 2.0
INFO:root:    gccPHATNLAlpha: 2.0
INFO:root:    gccPHATNLEnabled: False
INFO:root:NMF
INFO:root:    dictionarySize: 64
INFO:root:    dictionaryType: Pretrained
INFO:root:    numHUpdates: 0
INFO:root:    dictionarySizes: [64, 128, 256, 512, 1024]
INFO:root:Audio
INFO:root:    deviceIndex: None
INFO:root:    sampleRate: 44100
INFO:root:    numChannels: 2
INFO:root:STFT
INFO:root:    blockSize: 512
INFO:root:    windowSize: 1024
INFO:root:    hopSize: 512
INFO:root:GCCNMFPretraining: Loading pretrained W (size 64): ./pretrainedW\W_64.
npy
INFO:root:GCCNMFPretraining: Loading pretrained W (size 128): ./pretrainedW\W_12
8.npy
INFO:root:GCCNMFPretraining: Loading pretrained W (size 256): ./pretrainedW\W_25
6.npy
INFO:root:GCCNMFPretraining: Loading pretrained W (size 512): ./pretrainedW\W_51
2.npy
INFO:root:GCCNMFPretraining: Loading pretrained W (size 1024): ./pretrainedW\W_1
024.npy
INFO:root:RealtimeGCCNMF: Starting with audio path: ./test.wav
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be remove
d in the next release (v0.10).  Please switch to the gpuarray backend. You can g
et more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpua
rray%29

WARNING:theano.sandbox.cuda:The cuda backend is deprecated and will be removed i
n the next release (v0.10).  Please switch to the gpuarray backend. You can get
more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpua
rray%29

Using gpu device 0: GeForce GTX 860M (CNMeM is enabled with initial size: 70.0%
of memory, cuDNN 5005)
INFO:root:GCCNMFConfig: loading configuration params...
INFO:root:TDOA
INFO:root:    targetTDOAEpsilon: 5.0
INFO:root:    targetTDOANoiseFloor: 0.0
INFO:root:    numSpectrogramHistory: 128
INFO:root:    microphoneSeparationInMetres: 0.1
INFO:root:    numTDOAs: 64
INFO:root:    numTDOAHistory: 128
INFO:root:    targetTDOABeta: 2.0
INFO:root:    gccPHATNLAlpha: 2.0
INFO:root:    gccPHATNLEnabled: False
INFO:root:NMF
INFO:root:    dictionarySize: 64
INFO:root:    dictionaryType: Pretrained
INFO:root:    numHUpdates: 0
INFO:root:    dictionarySizes: [64, 128, 256, 512, 1024]
INFO:root:Audio
INFO:root:    deviceIndex: None
INFO:root:    sampleRate: 44100
INFO:root:    numChannels: 2
INFO:root:STFT
INFO:root:    blockSize: 512
INFO:root:    windowSize: 1024
INFO:root:    hopSize: 512
INFO:root:GCCNMFPretraining: Loading pretrained W (size 64): ./pretrainedW\W_64.
npy
INFO:root:GCCNMFPretraining: Loading pretrained W (size 128): ./pretrainedW\W_12
8.npy
INFO:root:GCCNMFPretraining: Loading pretrained W (size 256): ./pretrainedW\W_25
6.npy
INFO:root:GCCNMFPretraining: Loading pretrained W (size 512): ./pretrainedW\W_51
2.npy
INFO:root:GCCNMFPretraining: Loading pretrained W (size 1024): ./pretrainedW\W_1
024.npy
INFO:root:RealtimeGCCNMF: Starting with audio path: ./test.wav
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be remove
d in the next release (v0.10).  Please switch to the gpuarray backend. You can g
et more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpua
rray%29

WARNING:theano.sandbox.cuda:The cuda backend is deprecated and will be removed i
n the next release (v0.10).  Please switch to the gpuarray backend. You can get
more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpua
rray%29

Using gpu device 0: GeForce GTX 860M (CNMeM is enabled with initial size: 70.0%
of memory, cuDNN 5005)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\lib\multiprocessing\forking.py", line 509, in prepare
    '__parents_main__', file, path_name, etc
  File "C:\gccNMF\demo5.py", line 5, in <module>
    RealtimeGCCNMF()
  File "C:\gccNMF\runRealtimeGCCNMF.py", line 50, in __init__
    self.initProcesses(params)
  File "C:\gccNMF\runRealtimeGCCNMF.py", line 91, in initProcesses
    self.audioProcess.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 258, in __init__
    cmd = get_command_line() + [rhandle]
  File "C:\Python27\lib\multiprocessing\forking.py", line 358, in get_command_li
ne
    is not going to be frozen to produce a Windows executable.''')
RuntimeError:
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.

            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.
Traceback (most recent call last):
  File "demo5.py", line 5, in <module>
    RealtimeGCCNMF()
  File "C:\gccNMF\runRealtimeGCCNMF.py", line 50, in __init__
    self.initProcesses(params)
  File "C:\gccNMF\runRealtimeGCCNMF.py", line 91, in initProcesses
    self.audioProcess.start()
  File "C:\Python27\lib\multiprocessing\process.py", line 130, in start
    self._popen = Popen(self)
  File "C:\Python27\lib\multiprocessing\forking.py", line 277, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\Python27\lib\multiprocessing\forking.py", line 199, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Python27\lib\pickle.py", line 224, in dump
    self.save(obj)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "C:\Python27\lib\pickle.py", line 687, in _batch_setitems
    save(v)
  File "C:\Python27\lib\pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Python27\lib\pickle.py", line 425, in save_reduce
    save(state)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 568, in save_tuple
    save(element)
  File "C:\Python27\lib\pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Python27\lib\pickle.py", line 492, in save_string
    self.write(BINSTRING + pack("<i", n) + obj)
IOError: [Errno 22] Invalid argument

what is wrong? thanks!

**Comment by seanwood** [comment]
Thanks again for your help! Looks like the problem stems from multiprocessing with Python on Windows. Unfortunately, I am only able to test on Mac and Linux at the moment.

We should first try the suggestion that appears near the end of the error messages, i.e. wrapping the script in `if __name__ == '__main__'`, and calling `freeze_support`. Something like:

```
from multiprocessing import freeze_support
from gccNMF.realtime.runRealtimeGCCNMF import RealtimeGCCNMF

if __name__ == '__main__':
    freeze_support()
    RealtimeGCCNMF()
```

**Comment by dankorg** [comment]
Thank you, that actually worked. So one last question, is this mainly just for demonstration purposes as a real-time app or is there a way, after setting the correct real-time parameters, to actually click a button for example called process, and it will save the enhanced wav file on disk? Thanks!

**Comment by seanwood** [comment]
Excellent 👍 

Good idea for the save functionality! Instead of passing everything through the audio system as we do for the real-time playback, it's probably best to have a stand-alone function that gets called internally when you click "process". I'll look into that.
